#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pogrebok.Resource", IsApplication=true)]

namespace Pogrebok
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int alpha = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int trans = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonNormal = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonPressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttons = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_pog = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int NewButtons = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pogrebok_blur = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pogrebokSplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Power_off = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Power_On = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int separator = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int SplashWeather_blur = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int TileSeparator = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int TileSeparator_grad = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08002e
			public const int CountTurnOnText = 2131230766;
			
			// aapt resource value: 0x7f080001
			public const int DatePciker = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int DateText = 2131230730;
			
			// aapt resource value: 0x7f080059
			public const int Date_0 = 2131230809;
			
			// aapt resource value: 0x7f08005a
			public const int Date_1 = 2131230810;
			
			// aapt resource value: 0x7f08005b
			public const int Date_2 = 2131230811;
			
			// aapt resource value: 0x7f08005c
			public const int Date_3 = 2131230812;
			
			// aapt resource value: 0x7f08005d
			public const int Date_4 = 2131230813;
			
			// aapt resource value: 0x7f08005e
			public const int Date_5 = 2131230814;
			
			// aapt resource value: 0x7f08005f
			public const int Date_6 = 2131230815;
			
			// aapt resource value: 0x7f080060
			public const int Date_7 = 2131230816;
			
			// aapt resource value: 0x7f080061
			public const int Date_8 = 2131230817;
			
			// aapt resource value: 0x7f080062
			public const int Date_9 = 2131230818;
			
			// aapt resource value: 0x7f080000
			public const int Datecal = 2131230720;
			
			// aapt resource value: 0x7f080063
			public const int Day_0 = 2131230819;
			
			// aapt resource value: 0x7f080064
			public const int Day_1 = 2131230820;
			
			// aapt resource value: 0x7f080065
			public const int Day_2 = 2131230821;
			
			// aapt resource value: 0x7f080066
			public const int Day_3 = 2131230822;
			
			// aapt resource value: 0x7f080067
			public const int Day_4 = 2131230823;
			
			// aapt resource value: 0x7f080068
			public const int Day_5 = 2131230824;
			
			// aapt resource value: 0x7f080069
			public const int Day_6 = 2131230825;
			
			// aapt resource value: 0x7f08006a
			public const int Day_7 = 2131230826;
			
			// aapt resource value: 0x7f08006b
			public const int Day_8 = 2131230827;
			
			// aapt resource value: 0x7f08006c
			public const int Day_9 = 2131230828;
			
			// aapt resource value: 0x7f08002f
			public const int GetDataButton = 2131230767;
			
			// aapt resource value: 0x7f080002
			public const int MaxTempDateCal = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int MinTempDateCal = 2131230723;
			
			// aapt resource value: 0x7f080036
			public const int Pressure = 2131230774;
			
			// aapt resource value: 0x7f080016
			public const int PressureText = 2131230742;
			
			// aapt resource value: 0x7f080039
			public const int PriceEE = 2131230777;
			
			// aapt resource value: 0x7f08002b
			public const int PricePower = 2131230763;
			
			// aapt resource value: 0x7f080037
			public const int RashodEE = 2131230775;
			
			// aapt resource value: 0x7f08003b
			public const int Refresh = 2131230779;
			
			// aapt resource value: 0x7f08001f
			public const int TempCellarText = 2131230751;
			
			// aapt resource value: 0x7f080031
			public const int TempHome = 2131230769;
			
			// aapt resource value: 0x7f080010
			public const int TempHomeText = 2131230736;
			
			// aapt resource value: 0x7f080034
			public const int TempMax = 2131230772;
			
			// aapt resource value: 0x7f080019
			public const int TempMaxText = 2131230745;
			
			// aapt resource value: 0x7f080035
			public const int TempMin = 2131230773;
			
			// aapt resource value: 0x7f08001c
			public const int TempMinText = 2131230748;
			
			// aapt resource value: 0x7f080033
			public const int TempPogrebok = 2131230771;
			
			// aapt resource value: 0x7f080032
			public const int TempStreet = 2131230770;
			
			// aapt resource value: 0x7f080013
			public const int TempStreetText = 2131230739;
			
			// aapt resource value: 0x7f080025
			public const int TimePowerText = 2131230757;
			
			// aapt resource value: 0x7f08000d
			public const int TimeText = 2131230733;
			
			// aapt resource value: 0x7f080038
			public const int TimeWarm = 2131230776;
			
			// aapt resource value: 0x7f080022
			public const int WarmTurnText = 2131230754;
			
			// aapt resource value: 0x7f08003d
			public const int butsOnOff = 2131230781;
			
			// aapt resource value: 0x7f08003c
			public const int buttWeather = 2131230780;
			
			// aapt resource value: 0x7f080049
			public const int cityHumidity = 2131230793;
			
			// aapt resource value: 0x7f08004f
			public const int cityPressure = 2131230799;
			
			// aapt resource value: 0x7f080052
			public const int citySunRise = 2131230802;
			
			// aapt resource value: 0x7f080055
			public const int citySunset = 2131230805;
			
			// aapt resource value: 0x7f080043
			public const int cityTemp = 2131230787;
			
			// aapt resource value: 0x7f08004c
			public const int cityVisible = 2131230796;
			
			// aapt resource value: 0x7f080046
			public const int cityWind = 2131230790;
			
			// aapt resource value: 0x7f08003a
			public const int countTurnOn = 2131230778;
			
			// aapt resource value: 0x7f08003e
			public const int dateUpdate = 2131230782;
			
			// aapt resource value: 0x7f080030
			public const int horizontalScrollView1 = 2131230768;
			
			// aapt resource value: 0x7f080006
			public const int hscroll = 2131230726;
			
			// aapt resource value: 0x7f080028
			public const int kwtFullText = 2131230760;
			
			// aapt resource value: 0x7f080040
			public const int linearLayout1 = 2131230784;
			
			// aapt resource value: 0x7f080057
			public const int linearLayout2 = 2131230807;
			
			// aapt resource value: 0x7f080083
			public const int menuClose = 2131230851;
			
			// aapt resource value: 0x7f080081
			public const int menuTempMax = 2131230849;
			
			// aapt resource value: 0x7f080082
			public const int menuTempMin = 2131230850;
			
			// aapt resource value: 0x7f080005
			public const int scrollView1 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int tableLayout1 = 2131230727;
			
			// aapt resource value: 0x7f080058
			public const int tableLayout2 = 2131230808;
			
			// aapt resource value: 0x7f080008
			public const int tableRow1 = 2131230728;
			
			// aapt resource value: 0x7f080023
			public const int tableRow10 = 2131230755;
			
			// aapt resource value: 0x7f080026
			public const int tableRow11 = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int tableRow12 = 2131230761;
			
			// aapt resource value: 0x7f08002c
			public const int tableRow13 = 2131230764;
			
			// aapt resource value: 0x7f08000b
			public const int tableRow2 = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int tableRow3 = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int tableRow4 = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int tableRow5 = 2131230740;
			
			// aapt resource value: 0x7f080017
			public const int tableRow6 = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int tableRow7 = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int tableRow8 = 2131230749;
			
			// aapt resource value: 0x7f080020
			public const int tableRow9 = 2131230752;
			
			// aapt resource value: 0x7f08006d
			public const int tempHigh_0 = 2131230829;
			
			// aapt resource value: 0x7f08006e
			public const int tempHigh_1 = 2131230830;
			
			// aapt resource value: 0x7f08006f
			public const int tempHigh_2 = 2131230831;
			
			// aapt resource value: 0x7f080070
			public const int tempHigh_3 = 2131230832;
			
			// aapt resource value: 0x7f080071
			public const int tempHigh_4 = 2131230833;
			
			// aapt resource value: 0x7f080072
			public const int tempHigh_5 = 2131230834;
			
			// aapt resource value: 0x7f080073
			public const int tempHigh_6 = 2131230835;
			
			// aapt resource value: 0x7f080074
			public const int tempHigh_7 = 2131230836;
			
			// aapt resource value: 0x7f080075
			public const int tempHigh_8 = 2131230837;
			
			// aapt resource value: 0x7f080076
			public const int tempHigh_9 = 2131230838;
			
			// aapt resource value: 0x7f080077
			public const int tempLow_0 = 2131230839;
			
			// aapt resource value: 0x7f080078
			public const int tempLow_1 = 2131230840;
			
			// aapt resource value: 0x7f080079
			public const int tempLow_2 = 2131230841;
			
			// aapt resource value: 0x7f08007a
			public const int tempLow_3 = 2131230842;
			
			// aapt resource value: 0x7f08007b
			public const int tempLow_4 = 2131230843;
			
			// aapt resource value: 0x7f08007c
			public const int tempLow_5 = 2131230844;
			
			// aapt resource value: 0x7f08007d
			public const int tempLow_6 = 2131230845;
			
			// aapt resource value: 0x7f08007e
			public const int tempLow_7 = 2131230846;
			
			// aapt resource value: 0x7f08007f
			public const int tempLow_8 = 2131230847;
			
			// aapt resource value: 0x7f080080
			public const int tempLow_9 = 2131230848;
			
			// aapt resource value: 0x7f08003f
			public const int textPref = 2131230783;
			
			// aapt resource value: 0x7f08004e
			public const int textVie29 = 2131230798;
			
			// aapt resource value: 0x7f080050
			public const int textVie35 = 2131230800;
			
			// aapt resource value: 0x7f080041
			public const int textView1 = 2131230785;
			
			// aapt resource value: 0x7f080021
			public const int textView10 = 2131230753;
			
			// aapt resource value: 0x7f080024
			public const int textView11 = 2131230756;
			
			// aapt resource value: 0x7f080027
			public const int textView12 = 2131230759;
			
			// aapt resource value: 0x7f08002a
			public const int textView13 = 2131230762;
			
			// aapt resource value: 0x7f08002d
			public const int textView14 = 2131230765;
			
			// aapt resource value: 0x7f080009
			public const int textView2 = 2131230729;
			
			// aapt resource value: 0x7f080042
			public const int textView24 = 2131230786;
			
			// aapt resource value: 0x7f080045
			public const int textView25 = 2131230789;
			
			// aapt resource value: 0x7f080048
			public const int textView26 = 2131230792;
			
			// aapt resource value: 0x7f08004b
			public const int textView27 = 2131230795;
			
			// aapt resource value: 0x7f080051
			public const int textView28 = 2131230801;
			
			// aapt resource value: 0x7f080054
			public const int textView29 = 2131230804;
			
			// aapt resource value: 0x7f08000c
			public const int textView3 = 2131230732;
			
			// aapt resource value: 0x7f080044
			public const int textView30 = 2131230788;
			
			// aapt resource value: 0x7f080047
			public const int textView31 = 2131230791;
			
			// aapt resource value: 0x7f08004a
			public const int textView32 = 2131230794;
			
			// aapt resource value: 0x7f08004d
			public const int textView33 = 2131230797;
			
			// aapt resource value: 0x7f080053
			public const int textView34 = 2131230803;
			
			// aapt resource value: 0x7f080056
			public const int textView35 = 2131230806;
			
			// aapt resource value: 0x7f08000f
			public const int textView4 = 2131230735;
			
			// aapt resource value: 0x7f080012
			public const int textView5 = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int textView6 = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int textView7 = 2131230744;
			
			// aapt resource value: 0x7f08001b
			public const int textView8 = 2131230747;
			
			// aapt resource value: 0x7f08001e
			public const int textView9 = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int text_header = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataPicker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainTiles = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PrefLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int WeatherScreen = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menuTemp = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int AmountHours = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int AppId = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int EnergyConsumption = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int Forecast = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int Pressure = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int PriceEnergy = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Refresh = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int Report = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int TempHome = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int TempPogrebok = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int TempStreet = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int gradus = 2131034125;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_MainPage = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
