#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pogrebok.Resource", IsApplication=true)]

namespace Pogrebok
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_pog = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pogrebokSplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060029
			public const int CountTurnOnText = 2131099689;
			
			// aapt resource value: 0x7f060005
			public const int DateText = 2131099653;
			
			// aapt resource value: 0x7f06002a
			public const int GetDataButton = 2131099690;
			
			// aapt resource value: 0x7f060011
			public const int PressureText = 2131099665;
			
			// aapt resource value: 0x7f060026
			public const int PricePower = 2131099686;
			
			// aapt resource value: 0x7f06001a
			public const int TempCellarText = 2131099674;
			
			// aapt resource value: 0x7f06000b
			public const int TempHomeText = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int TempMaxText = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int TempMinText = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int TempStreetText = 2131099662;
			
			// aapt resource value: 0x7f060020
			public const int TimePowerText = 2131099680;
			
			// aapt resource value: 0x7f060008
			public const int TimeText = 2131099656;
			
			// aapt resource value: 0x7f06001d
			public const int WarmTurnText = 2131099677;
			
			// aapt resource value: 0x7f060001
			public const int hscroll = 2131099649;
			
			// aapt resource value: 0x7f060023
			public const int kwtFullText = 2131099683;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int tableLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tableRow1 = 2131099651;
			
			// aapt resource value: 0x7f06001e
			public const int tableRow10 = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int tableRow11 = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int tableRow12 = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int tableRow13 = 2131099687;
			
			// aapt resource value: 0x7f060006
			public const int tableRow2 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int tableRow3 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow4 = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow5 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int tableRow6 = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int tableRow7 = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int tableRow8 = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int tableRow9 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int textView10 = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int textView11 = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int textView12 = 2131099682;
			
			// aapt resource value: 0x7f060025
			public const int textView13 = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int textView14 = 2131099688;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int textView4 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int textView5 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int textView6 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int textView7 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int textView8 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int textView9 = 2131099673;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_MainPage = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
