#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pogrebok.Resource", IsApplication=true)]

namespace Pogrebok
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int alpha = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int trans = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonNormal = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonPressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttons = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_pog = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int NewButtons = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pogrebok_blur = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pogrebokSplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Power_off = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Power_On = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int separator = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int SplashWeather_blur = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int TileSeparator = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int TileSeparator_grad = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002a
			public const int CountTurnOnText = 2131165226;
			
			// aapt resource value: 0x7f070006
			public const int DateText = 2131165190;
			
			// aapt resource value: 0x7f070055
			public const int Date_0 = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int Date_1 = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int Date_2 = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int Date_3 = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int Date_4 = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int Date_5 = 2131165274;
			
			// aapt resource value: 0x7f07005b
			public const int Date_6 = 2131165275;
			
			// aapt resource value: 0x7f07005c
			public const int Date_7 = 2131165276;
			
			// aapt resource value: 0x7f07005d
			public const int Date_8 = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int Date_9 = 2131165278;
			
			// aapt resource value: 0x7f07005f
			public const int Day_0 = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int Day_1 = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int Day_2 = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int Day_3 = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int Day_4 = 2131165283;
			
			// aapt resource value: 0x7f070064
			public const int Day_5 = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int Day_6 = 2131165285;
			
			// aapt resource value: 0x7f070066
			public const int Day_7 = 2131165286;
			
			// aapt resource value: 0x7f070067
			public const int Day_8 = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int Day_9 = 2131165288;
			
			// aapt resource value: 0x7f07002b
			public const int GetDataButton = 2131165227;
			
			// aapt resource value: 0x7f070032
			public const int Pressure = 2131165234;
			
			// aapt resource value: 0x7f070012
			public const int PressureText = 2131165202;
			
			// aapt resource value: 0x7f070035
			public const int PriceEE = 2131165237;
			
			// aapt resource value: 0x7f070027
			public const int PricePower = 2131165223;
			
			// aapt resource value: 0x7f070033
			public const int RashodEE = 2131165235;
			
			// aapt resource value: 0x7f070037
			public const int Refresh = 2131165239;
			
			// aapt resource value: 0x7f07001b
			public const int TempCellarText = 2131165211;
			
			// aapt resource value: 0x7f07002d
			public const int TempHome = 2131165229;
			
			// aapt resource value: 0x7f07000c
			public const int TempHomeText = 2131165196;
			
			// aapt resource value: 0x7f070030
			public const int TempMax = 2131165232;
			
			// aapt resource value: 0x7f070015
			public const int TempMaxText = 2131165205;
			
			// aapt resource value: 0x7f070031
			public const int TempMin = 2131165233;
			
			// aapt resource value: 0x7f070018
			public const int TempMinText = 2131165208;
			
			// aapt resource value: 0x7f07002f
			public const int TempPogrebok = 2131165231;
			
			// aapt resource value: 0x7f07002e
			public const int TempStreet = 2131165230;
			
			// aapt resource value: 0x7f07000f
			public const int TempStreetText = 2131165199;
			
			// aapt resource value: 0x7f070021
			public const int TimePowerText = 2131165217;
			
			// aapt resource value: 0x7f070009
			public const int TimeText = 2131165193;
			
			// aapt resource value: 0x7f070034
			public const int TimeWarm = 2131165236;
			
			// aapt resource value: 0x7f07001e
			public const int WarmTurnText = 2131165214;
			
			// aapt resource value: 0x7f070039
			public const int butsOnOff = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int buttWeather = 2131165240;
			
			// aapt resource value: 0x7f070045
			public const int cityHumidity = 2131165253;
			
			// aapt resource value: 0x7f07004b
			public const int cityPressure = 2131165259;
			
			// aapt resource value: 0x7f07004e
			public const int citySunRise = 2131165262;
			
			// aapt resource value: 0x7f070051
			public const int citySunset = 2131165265;
			
			// aapt resource value: 0x7f07003f
			public const int cityTemp = 2131165247;
			
			// aapt resource value: 0x7f070048
			public const int cityVisible = 2131165256;
			
			// aapt resource value: 0x7f070042
			public const int cityWind = 2131165250;
			
			// aapt resource value: 0x7f070036
			public const int countTurnOn = 2131165238;
			
			// aapt resource value: 0x7f07003a
			public const int dateUpdate = 2131165242;
			
			// aapt resource value: 0x7f07002c
			public const int horizontalScrollView1 = 2131165228;
			
			// aapt resource value: 0x7f070002
			public const int hscroll = 2131165186;
			
			// aapt resource value: 0x7f070024
			public const int kwtFullText = 2131165220;
			
			// aapt resource value: 0x7f07003c
			public const int linearLayout1 = 2131165244;
			
			// aapt resource value: 0x7f070053
			public const int linearLayout2 = 2131165267;
			
			// aapt resource value: 0x7f070001
			public const int scrollView1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int tableLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070054
			public const int tableLayout2 = 2131165268;
			
			// aapt resource value: 0x7f070004
			public const int tableRow1 = 2131165188;
			
			// aapt resource value: 0x7f07001f
			public const int tableRow10 = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int tableRow11 = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int tableRow12 = 2131165221;
			
			// aapt resource value: 0x7f070028
			public const int tableRow13 = 2131165224;
			
			// aapt resource value: 0x7f070007
			public const int tableRow2 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int tableRow3 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int tableRow4 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int tableRow5 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int tableRow6 = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int tableRow7 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int tableRow8 = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int tableRow9 = 2131165212;
			
			// aapt resource value: 0x7f070069
			public const int tempHigh_0 = 2131165289;
			
			// aapt resource value: 0x7f07006a
			public const int tempHigh_1 = 2131165290;
			
			// aapt resource value: 0x7f07006b
			public const int tempHigh_2 = 2131165291;
			
			// aapt resource value: 0x7f07006c
			public const int tempHigh_3 = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int tempHigh_4 = 2131165293;
			
			// aapt resource value: 0x7f07006e
			public const int tempHigh_5 = 2131165294;
			
			// aapt resource value: 0x7f07006f
			public const int tempHigh_6 = 2131165295;
			
			// aapt resource value: 0x7f070070
			public const int tempHigh_7 = 2131165296;
			
			// aapt resource value: 0x7f070071
			public const int tempHigh_8 = 2131165297;
			
			// aapt resource value: 0x7f070072
			public const int tempHigh_9 = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int tempLow_0 = 2131165299;
			
			// aapt resource value: 0x7f070074
			public const int tempLow_1 = 2131165300;
			
			// aapt resource value: 0x7f070075
			public const int tempLow_2 = 2131165301;
			
			// aapt resource value: 0x7f070076
			public const int tempLow_3 = 2131165302;
			
			// aapt resource value: 0x7f070077
			public const int tempLow_4 = 2131165303;
			
			// aapt resource value: 0x7f070078
			public const int tempLow_5 = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int tempLow_6 = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int tempLow_7 = 2131165306;
			
			// aapt resource value: 0x7f07007b
			public const int tempLow_8 = 2131165307;
			
			// aapt resource value: 0x7f07007c
			public const int tempLow_9 = 2131165308;
			
			// aapt resource value: 0x7f07003b
			public const int textPref = 2131165243;
			
			// aapt resource value: 0x7f07004a
			public const int textVie29 = 2131165258;
			
			// aapt resource value: 0x7f07004c
			public const int textVie35 = 2131165260;
			
			// aapt resource value: 0x7f07003d
			public const int textView1 = 2131165245;
			
			// aapt resource value: 0x7f07001d
			public const int textView10 = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int textView11 = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int textView12 = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int textView13 = 2131165222;
			
			// aapt resource value: 0x7f070029
			public const int textView14 = 2131165225;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f07003e
			public const int textView24 = 2131165246;
			
			// aapt resource value: 0x7f070041
			public const int textView25 = 2131165249;
			
			// aapt resource value: 0x7f070044
			public const int textView26 = 2131165252;
			
			// aapt resource value: 0x7f070047
			public const int textView27 = 2131165255;
			
			// aapt resource value: 0x7f07004d
			public const int textView28 = 2131165261;
			
			// aapt resource value: 0x7f070050
			public const int textView29 = 2131165264;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			// aapt resource value: 0x7f070040
			public const int textView30 = 2131165248;
			
			// aapt resource value: 0x7f070043
			public const int textView31 = 2131165251;
			
			// aapt resource value: 0x7f070046
			public const int textView32 = 2131165254;
			
			// aapt resource value: 0x7f070049
			public const int textView33 = 2131165257;
			
			// aapt resource value: 0x7f07004f
			public const int textView34 = 2131165263;
			
			// aapt resource value: 0x7f070052
			public const int textView35 = 2131165266;
			
			// aapt resource value: 0x7f07000b
			public const int textView4 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int textView5 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int textView6 = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int textView7 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int textView8 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int textView9 = 2131165210;
			
			// aapt resource value: 0x7f070000
			public const int text_header = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainTiles = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PrefLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int WeatherScreen = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int AppId = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_MainPage = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
